// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdbwjasojowqmmhzehgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYndqYXNvam93cW1taHplaGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTQ1MTQsImV4cCI6MjA1ODgzMDUxNH0.e6XdrRXLhKDHfSW4MUNAMwHiMKhY0UQVbIFpOTxUsyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);